"""empty message

Revision ID: 55480c576f00
Revises: 153a54caa6bc
Create Date: 2024-06-13 09:37:05.213392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55480c576f00'
down_revision = '153a54caa6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
